on:
  push:
    branches:
      - main

env:
  TAG: ref-${{ github.ref_name }}

jobs:
  docker-build:
    timeout-minutes: 360
    runs-on: ${{ matrix.runs_on }}
    continue-on-error: ${{ matrix.continue-on-error || false }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - runs_on: ubuntu-24.04-arm
            arch: arm64
          - runs_on: ubuntu-24.04
            arch: amd64
            continue_on_error: true
    env:
      ARCH: ${{ matrix.arch }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Run command
      run: "${{ !matrix.continue_on_error }}"
      continue-on-error: ${{ matrix.continue_on_error || false }}
    - uses: actions/upload-artifact@v4
      with:
        name: proxmox-ve-${{ matrix.arch }}
        path: release/*.tgz
    - name: Run docker push for ${{matrix.arch}}
      run: "true"

  manifest:
    runs-on: ubuntu-latest
    needs: [docker-build]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Create manifest
      run: "true"
